dofile("game_object.lua")
dofile("input_defines.lua")
dofile("game_config.lua")
dofile("game_loop.lua")
dofile("world.lua")
dofile("planet.lua")
dofile("player.lua")
dofile("background_obj.lua")

game_window:set_clear_color(0.0, 0.0, 0.0)
bind_actions(game_bindings)

game_loop(function (seconds) 
	world.start_frame(seconds)
		planet.update(seconds)
		player.update(seconds)
		background_object:update(seconds)
	world.end_frame(seconds)
end)